### ISSUE TITLE
Manipulating input image

### ISSUE THREAD

**Issue by me-Stoffel** [teichgraf/WinMLExperiments#4]
Hey Rene,

great work, the example scene and ML model works fine! I have not really an issue but more of a question: I'd like to grab the camera image and manipulate it (using openCV), before using it with an ONNX model. However I'm badly stuck at trying to set up the input for the model coming from an Unity Texture2D (getting to the Windows specific Videoframe). Did you by chance try something like that or have some insights how to do that?

Best regards
Stoffel

**Comment by reneschulte** [comment]
You might want to inverse that if possible. Unity can also use a pointer to a native system texture as Texture, so you could use an D3D surface with MediaCapture / VideoFrame and pass that into Unity directly.
https://docs.microsoft.com/en-us/uwp/api/windows.media.capture.frames.mediaframereader.tryacquirelatestframe#Windows_Media_Capture_Frames_MediaFrameReader_TryAcquireLatestFrame

This might be the fastest approach but not sure if that works end-to-end. I know we are using a native Unity texture ptr with one of our solutions to fill in the data directly on the GPU from Windows MF video decoding.

Otherwise you might have to do a texture conversion manually. 
https://docs.unity3d.com/ScriptReference/Texture2D.SetPixels32.html

**Comment by me-Stoffel** [comment]
Thanks a lot for the quick response! :)

Doing the inverse seems more straight forward, but as I want to feed the result back to the machine learning model, after manipulating it in Unity, I think I need to go from Texture2D to VideoFrame. I need the Texture2D format for my current implementation using OpenCV, which I basically use to do some preprocessing on the images. Or is there any other input option to trigger the Windows specific functions? I have the camera input and preprocessing set up and it works fine already e.g. with Azure Custom Vision, "just" want to try to make it offline available now.

Currently I'm trying to get from Texture2D to VideoFrame by setting up a WriteableBitmap, writing the byte array from the Texture2D to it via its PixelBuffer and then use CopyFromBuffer to populate the SoftwareBitmap of a newly created VideoFrame. Haven't gotten anywhere useable so far, but will keep trying ;)

Do you think this would work in general, or am I missing/misunderstanding something?

**Comment by reneschulte** [comment]
Yes, I think this should work. Might just not be very efficient and fast. :) 

You might at least be able to circumvent Unity's Texture2D with your OpenCV implementation. I'm sure there's another bitmap copy involved there which is expensive. OpenCV works on a pixel buffer internally so hopefully you can get it directly. Otherwise Texture2D provides the GetPixels method to get the pixel buffer copied. And yes, then you can feed that into a SoftwareBitmap via an IBuffer. 
https://docs.microsoft.com/en-us/uwp/api/windows.media.videoframe.createwithsoftwarebitmap#Windows_Media_VideoFrame_CreateWithSoftwareBitmap_Windows_Graphics_Imaging_SoftwareBitmap_ 

That you can then use to create a VideoFrame:
https://docs.microsoft.com/en-us/uwp/api/windows.graphics.imaging.softwarebitmap

Maybe it also works that you can get a reference to the VideoFrame's internal SoftwareBitmap and avoid creating a new instance but might be you have to use the static method:
public static VideoFrame CreateWithSoftwareBitmap(SoftwareBitmap bitmap) 

Also make sure to pay attention to the pixel formats you are dealing with and ensure these match.

Good luck.
